FROM kolla/centos-source-skydive-base:9.1.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="skydive-agent" build-date="20200211"









    



RUN yum -y install openvswitch \
    && yum clean all && rm -rf /var/cache/yum




