FROM kolla/centos-source-swift-base:9.1.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="swift-proxy-server" build-date="20200211"









RUN pip --no-cache-dir install --upgrade -c /requirements/upper-constraints.txt ceilometermiddleware






USER swift