FROM kolla/centos-source-sahara-base:9.1.0
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="sahara-engine" build-date="20200211"






    
       
    


RUN yum -y install nc \
    && yum clean all && rm -rf /var/cache/yum




USER sahara